// =============================================================================
// tests/search.test.ts — AUTO-GENERATED TEST SUITE
// =============================================================================
// SOURCE USER STORY: US-05 — Search Functionality
// GENERATED BY: npm run generate
//
// ⚠️  REVIEW & CUSTOMIZE:
//   This file was auto-generated from the user story YAML.
//   You should review each test and:
//     1. Verify the page object methods match your application
//     2. Add additional assertions specific to your UI
//     3. Adjust selectors in the Page Object if needed
// =============================================================================

import { test, expect } from '../utils/framework/xray-test-fixture';
import { SearchPage } from '../pages/SearchPage';
import { enhancedLogger } from '../utils/helpers/enhanced-logger';
import { getTestData, getTestDataSets, isTestEnabled } from '../utils/helpers/test-data-loader';

const DATA_FILE = 'search-tests.yaml';

// =============================================================================
// TEST GROUP: Search Feature Tests
// =============================================================================
test.describe('Search Feature Tests', () => {

  // ── TC14: Search for a valid keyword and verify results appear ──
  const proj201Enabled = isTestEnabled(DATA_FILE, 'PROJ-201');
  const proj201Sets    = getTestDataSets(DATA_FILE, 'PROJ-201');

  for (const ds of proj201Sets) {
    test(
      `TC14: Search for a valid keyword and verify results appear [${ds.label}]`,
      {
        annotation: { type: 'xray', description: 'PROJ-201' },
      },
      async ({ page, xrayTestKey }) => {
        if (!proj201Enabled) test.skip();

        enhancedLogger.section(`▶ Running Test: TC14 [${ds.label}] | XRAY: ${xrayTestKey}`);
        enhancedLogger.info(`📂 Test data loaded from ${DATA_FILE} for ${xrayTestKey} [${ds.label}]`, xrayTestKey);

        const searchPage = new SearchPage(page);

        // Step 1: Navigate to the documentation page
        enhancedLogger.step('Step 1: Navigate to the documentation page', xrayTestKey);
        await searchPage.navigateTo(ds.pagePath as string || '/docs/intro');
        enhancedLogger.info('✅ Page loaded', xrayTestKey);

        // Step 2: Click the search icon / press Ctrl+K to open search
        enhancedLogger.step('Step 2: Click the search icon / press Ctrl+K to open search', xrayTestKey);
        // TODO: Update selector for "search icon"
        await searchPage.performClick('search icon');
        enhancedLogger.info('✅ Clicked search icon', xrayTestKey);

        // Step 3: Type 'locator' into the search field
        enhancedLogger.step('Step 3: Type \'locator\' into the search field', xrayTestKey);
        // TODO: Update selector for "search"
        await searchPage.fillField('search', ds.searchKeyword as string);
        enhancedLogger.info(`✅ Entered "${ds.searchKeyword}" into search`, xrayTestKey);

        // Step 4: Verify at least one result contains the keyword
        enhancedLogger.step('Step 4: Verify at least one result contains the keyword', xrayTestKey);
        // TODO: Update the selector for search results
        const results = await searchPage.getResultCount();
        expect(results).toBeGreaterThanOrEqual(ds.expectedMinResults as number);
        enhancedLogger.info(`✅ Found ${results} results (expected ≥ ${ds.expectedMinResults})`, xrayTestKey);

        enhancedLogger.pass(`TC14 passed [${ds.label}]`, xrayTestKey);
      }
    );
  }

  // ── TC15: Search for an empty string should show no results or prompt ──
  const proj202Enabled = isTestEnabled(DATA_FILE, 'PROJ-202');
  const proj202Sets    = getTestDataSets(DATA_FILE, 'PROJ-202');

  for (const ds of proj202Sets) {
    test(
      `TC15: Search for an empty string should show no results or prompt [${ds.label}]`,
      {
        annotation: { type: 'xray', description: 'PROJ-202' },
      },
      async ({ page, xrayTestKey }) => {
        if (!proj202Enabled) test.skip();

        enhancedLogger.section(`▶ Running Test: TC15 [${ds.label}] | XRAY: ${xrayTestKey}`);
        enhancedLogger.info(`📂 Test data loaded from ${DATA_FILE} for ${xrayTestKey} [${ds.label}]`, xrayTestKey);

        const searchPage = new SearchPage(page);

        // Step 1: Navigate to the documentation page
        enhancedLogger.step('Step 1: Navigate to the documentation page', xrayTestKey);
        await searchPage.navigateTo(ds.pagePath as string || '/docs/intro');
        enhancedLogger.info('✅ Page loaded', xrayTestKey);

        // Step 2: Open the search modal
        enhancedLogger.step('Step 2: Open the search modal', xrayTestKey);
        // TODO: Update selector for "search modal"
        await searchPage.performClick('search modal');
        enhancedLogger.info('✅ Clicked search modal', xrayTestKey);

        // Step 3: Submit search with empty input
        enhancedLogger.step('Step 3: Submit search with empty input', xrayTestKey);
        // Submit with empty/blank input
        await searchPage.submitForm();
        enhancedLogger.info('✅ Form submitted with empty input', xrayTestKey);

        enhancedLogger.pass(`TC15 passed [${ds.label}]`, xrayTestKey);
      }
    );
  }

  // ── TC16: Search for a nonsense keyword should show no results ──
  const proj203Enabled = isTestEnabled(DATA_FILE, 'PROJ-203');
  const proj203Sets    = getTestDataSets(DATA_FILE, 'PROJ-203');

  for (const ds of proj203Sets) {
    test(
      `TC16: Search for a nonsense keyword should show no results [${ds.label}]`,
      {
        annotation: { type: 'xray', description: 'PROJ-203' },
      },
      async ({ page, xrayTestKey }) => {
        if (!proj203Enabled) test.skip();

        enhancedLogger.section(`▶ Running Test: TC16 [${ds.label}] | XRAY: ${xrayTestKey}`);
        enhancedLogger.info(`📂 Test data loaded from ${DATA_FILE} for ${xrayTestKey} [${ds.label}]`, xrayTestKey);

        const searchPage = new SearchPage(page);

        // Step 1: Navigate to the documentation page
        enhancedLogger.step('Step 1: Navigate to the documentation page', xrayTestKey);
        await searchPage.navigateTo(ds.pagePath as string || '/docs/intro');
        enhancedLogger.info('✅ Page loaded', xrayTestKey);

        // Step 2: Open the search modal
        enhancedLogger.step('Step 2: Open the search modal', xrayTestKey);
        // TODO: Update selector for "search modal"
        await searchPage.performClick('search modal');
        enhancedLogger.info('✅ Clicked search modal', xrayTestKey);

        // Step 3: Type 'xyzzynonexistent99' into the search field
        enhancedLogger.step('Step 3: Type \'xyzzynonexistent99\' into the search field', xrayTestKey);
        // TODO: Update selector for "search"
        await searchPage.fillField('search', ds.searchKeyword as string);
        enhancedLogger.info(`✅ Entered "${ds.searchKeyword}" into search`, xrayTestKey);

        enhancedLogger.pass(`TC16 passed [${ds.label}]`, xrayTestKey);
      }
    );
  }

});
