#!/usr/bin/env ts-node
// =============================================================================
// scripts/generate-from-stories.ts — AUTOMATED PIPELINE
// =============================================================================
// PURPOSE:
//   Reads User Story YAML files from user-stories/ and generates:
//     1. TEST_CASES.md  — appends new test cases with traceability
//     2. test-data/*.yaml — YAML test data for each user story
//     3. tests/*.test.ts  — Playwright test scripts
//     4. pages/*Page.ts   — Page Object Model files
//
// USAGE:
//   npm run generate                  → Full pipeline (TC + scripts)
//   npm run generate:tc               → Generate test cases + YAML only
//   npm run generate:scripts          → Generate test scripts + page objects only
//   npm run generate -- US-05-search  → Generate only for one story
//
// FLOW:
//   user-stories/US-05-search.yaml
//       │
//       ├──→ TEST_CASES.md          (test case documentation)
//       ├──→ test-data/search-tests.yaml  (YAML test data)
//       ├──→ tests/search.test.ts         (Playwright test script)
//       └──→ pages/SearchPage.ts          (Page Object class)
// =============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { parse as parseYaml } from 'yaml';

// ─────────────────────────────────────────────────────────────────────────────
//  TYPES
// ─────────────────────────────────────────────────────────────────────────────

interface TestStep {
  action: string;
  expected: string;
}

interface AcceptanceCriterion {
  id: string;          // PROJ-201
  tcId: string;        // TC14
  title: string;
  type: string;        // positive | negative | boundary | smoke
  priority: string;    // critical | high | medium | low
  preconditions: string[];
  steps: TestStep[];
  testData: Record<string, unknown>;
}

interface StoryOutput {
  dataFile: string;
  testFile: string;
  pageObject: string;
  testGroup: string;
}

interface UserStory {
  storyId: string;
  title: string;
  description: string;
  priority: string;
  module: string;
  baseUrl: string;
  pagePath: string;
  output: StoryOutput;
  acceptanceCriteria: AcceptanceCriterion[];
}

// ─────────────────────────────────────────────────────────────────────────────
//  PATHS
// ─────────────────────────────────────────────────────────────────────────────

const ROOT         = path.resolve(__dirname, '..');
const STORIES_DIR  = path.join(ROOT, 'user-stories');
const TEST_DATA_DIR= path.join(ROOT, 'test-data');
const TESTS_DIR    = path.join(ROOT, 'tests');
const PAGES_DIR    = path.join(ROOT, 'pages');
const TC_FILE      = path.join(ROOT, 'TEST_CASES.md');

// ─────────────────────────────────────────────────────────────────────────────
//  HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function banner(msg: string): void {
  console.log('\n' + '═'.repeat(70));
  console.log(`  ${msg}`);
  console.log('═'.repeat(70));
}

function info(msg: string): void {
  console.log(`  ✅ ${msg}`);
}

function warn(msg: string): void {
  console.log(`  ⚠️  ${msg}`);
}

function loadStory(filePath: string): UserStory {
  const raw = fs.readFileSync(filePath, 'utf-8');
  return parseYaml(raw) as UserStory;
}

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERATOR 1: TEST DATA YAML
// ─────────────────────────────────────────────────────────────────────────────

function generateTestDataYaml(story: UserStory): string {
  const lines: string[] = [];

  lines.push(`# ╔${'═'.repeat(73)}╗`);
  lines.push(`# ║  🔌 AUTO-GENERATED TEST DATA — ${story.output.dataFile.padEnd(40)}║`);
  lines.push(`# ║  From User Story: ${story.storyId} — ${story.title.padEnd(34).slice(0, 34)}          ║`);
  lines.push(`# ╠${'═'.repeat(73)}╣`);
  lines.push(`# ║  Generated by: npm run generate                                        ║`);
  lines.push(`# ║  Source: user-stories/${story.storyId.toLowerCase()}-*.yaml                              ║`);
  lines.push(`# ║                                                                         ║`);
  lines.push(`# ║  ⚠️  REVIEW & CUSTOMIZE: This is auto-generated. You should:             ║`);
  lines.push(`# ║     • Verify test data values match your application                    ║`);
  lines.push(`# ║     • Add encrypted passwords with \${ENC:...} if needed                 ║`);
  lines.push(`# ║     • Add dataSets: arrays for parameterized tests                      ║`);
  lines.push(`# ║     • Set run: no to skip any test case                                 ║`);
  lines.push(`# ╚${'═'.repeat(73)}╝`);
  lines.push('');
  lines.push('');

  for (const ac of story.acceptanceCriteria) {
    lines.push(`# ─── ${ac.tcId}: ${ac.title}`);
    lines.push(`${ac.id}:`);
    lines.push(`  run: yes`);
    lines.push(`  testCase: "${ac.tcId}: ${ac.title}"`);
    lines.push(`  type: "${ac.type}"`);
    lines.push(`  baseUrl: "${story.baseUrl}"`);
    lines.push(`  pagePath: "${story.pagePath}"`);

    // Write all test data fields
    for (const [key, value] of Object.entries(ac.testData)) {
      if (typeof value === 'string') {
        lines.push(`  ${key}: "${value}"`);
      } else if (typeof value === 'number' || typeof value === 'boolean') {
        lines.push(`  ${key}: ${value}`);
      } else if (Array.isArray(value)) {
        lines.push(`  ${key}:`);
        for (const item of value) {
          lines.push(`    - "${item}"`);
        }
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERATOR 2: TEST SCRIPT (.test.ts)
// ─────────────────────────────────────────────────────────────────────────────

function generateTestScript(story: UserStory): string {
  const po = story.output.pageObject;
  const poVar = toCamelCase(po.replace(/Page$/, '')) + 'Page';
  const lines: string[] = [];

  lines.push(`// =============================================================================`);
  lines.push(`// tests/${story.output.testFile} — AUTO-GENERATED TEST SUITE`);
  lines.push(`// =============================================================================`);
  lines.push(`// SOURCE USER STORY: ${story.storyId} — ${story.title}`);
  lines.push(`// GENERATED BY: npm run generate`);
  lines.push(`//`);
  lines.push(`// ⚠️  REVIEW & CUSTOMIZE:`);
  lines.push(`//   This file was auto-generated from the user story YAML.`);
  lines.push(`//   You should review each test and:`);
  lines.push(`//     1. Verify the page object methods match your application`);
  lines.push(`//     2. Add additional assertions specific to your UI`);
  lines.push(`//     3. Adjust selectors in the Page Object if needed`);
  lines.push(`// =============================================================================`);
  lines.push('');
  lines.push(`import { test, expect } from '../utils/framework/xray-test-fixture';`);
  lines.push(`import { ${po} } from '../pages/${po}';`);
  lines.push(`import { enhancedLogger } from '../utils/helpers/enhanced-logger';`);
  lines.push(`import { getTestData, getTestDataSets, isTestEnabled } from '../utils/helpers/test-data-loader';`);
  lines.push('');
  lines.push(`const DATA_FILE = '${story.output.dataFile}';`);
  lines.push('');
  lines.push(`// =============================================================================`);
  lines.push(`// TEST GROUP: ${story.output.testGroup}`);
  lines.push(`// =============================================================================`);
  lines.push(`test.describe('${story.output.testGroup}', () => {`);
  lines.push('');

  for (const ac of story.acceptanceCriteria) {
    lines.push(`  // ── ${ac.tcId}: ${ac.title} ──`);
    lines.push(`  const ${varName(ac.id)}Enabled = isTestEnabled(DATA_FILE, '${ac.id}');`);
    lines.push(`  const ${varName(ac.id)}Sets    = getTestDataSets(DATA_FILE, '${ac.id}');`);
    lines.push('');
    lines.push(`  for (const ds of ${varName(ac.id)}Sets) {`);
    lines.push(`    test(`);
    lines.push(`      \`${ac.tcId}: ${escapeTemplate(ac.title)} [\${ds.label}]\`,`);
    lines.push(`      {`);
    lines.push(`        annotation: { type: 'xray', description: '${ac.id}' },`);
    lines.push(`      },`);
    lines.push(`      async ({ page, xrayTestKey }) => {`);
    lines.push(`        if (!${varName(ac.id)}Enabled) test.skip();`);
    lines.push('');
    lines.push(`        enhancedLogger.section(\`▶ Running Test: ${ac.tcId} [\${ds.label}] | XRAY: \${xrayTestKey}\`);`);
    lines.push(`        enhancedLogger.info(\`📂 Test data loaded from \${DATA_FILE} for \${xrayTestKey} [\${ds.label}]\`, xrayTestKey);`);
    lines.push('');
    lines.push(`        const ${poVar} = new ${po}(page);`);
    lines.push('');

    // Generate steps from the user story
    for (let i = 0; i < ac.steps.length; i++) {
      const step = ac.steps[i]!;
      const stepNum = i + 1;
      lines.push(`        // Step ${stepNum}: ${step.action}`);
      lines.push(`        enhancedLogger.step('Step ${stepNum}: ${escapeQuotes(step.action)}', xrayTestKey);`);

      // Generate intelligent step code based on the action text
      const code = generateStepCode(step, ac, story, poVar, stepNum);
      for (const codeLine of code) {
        lines.push(`        ${codeLine}`);
      }
      lines.push('');
    }

    lines.push(`        enhancedLogger.pass(\`${ac.tcId} passed [\${ds.label}]\`, xrayTestKey);`);
    lines.push(`      }`);
    lines.push(`    );`);
    lines.push(`  }`);
    lines.push('');
  }

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
//  STEP CODE GENERATOR — maps user story actions to Playwright code
// ─────────────────────────────────────────────────────────────────────────────

function generateStepCode(
  step: TestStep,
  ac: AcceptanceCriterion,
  story: UserStory,
  poVar: string,
  stepNum: number,
): string[] {
  const action = step.action.toLowerCase();
  const code: string[] = [];

  // Helper: detect if "open" refers to a UI element (modal, dialog, dropdown) vs page navigation
  const isOpenUI = action.includes('open') &&
    (action.includes('modal') || action.includes('dialog') || action.includes('dropdown') ||
     action.includes('panel') || action.includes('menu') || action.includes('search') ||
     action.includes('popup') || action.includes('overlay'));

  // ── CLICK patterns (check BEFORE navigate — "click to open" is a click, not a navigate) ──
  if (action.includes('click') || action.includes('press') || action.includes('tap') || isOpenUI) {
    const target = extractTarget(step.action);
    code.push(`// TODO: Update selector for "${target}"`);
    code.push(`await ${poVar}.performClick('${target}');`);
    code.push(`enhancedLogger.info('✅ Clicked ${escapeQuotes(target)}', xrayTestKey);`);
  }

  // ── NAVIGATE patterns ──
  else if (action.includes('navigate') || action.includes('go to') || action.includes('load') || (action.includes('open') && !action.includes('click'))) {
    code.push(`await ${poVar}.navigateTo(ds.pagePath as string || '${story.pagePath}');`);
    code.push(`enhancedLogger.info('✅ Page loaded', xrayTestKey);`);
  }

  // ── SUBMIT patterns (check BEFORE type — "submit search" is a submit, not a type) ──
  else if (action.includes('submit')) {
    // If there's also a type action ("submit search with empty input"), fill then submit
    const dataKey = guessDataKey(step.action, ac.testData);
    if (action.includes('empty') || action.includes('blank')) {
      code.push(`// Submit with empty/blank input`);
      code.push(`await ${poVar}.submitForm();`);
      code.push(`enhancedLogger.info('✅ Form submitted with empty input', xrayTestKey);`);
    } else {
      code.push(`await ${poVar}.submitForm();`);
      code.push(`enhancedLogger.info('✅ Form submitted', xrayTestKey);`);
    }
  }

  // ── TYPE / ENTER / SEARCH patterns ──
  else if (action.includes('type') || action.includes('enter') || action.includes('search') || action.includes('input')) {
    const field = extractField(step.action);
    const dataKey = guessDataKey(step.action, ac.testData);
    code.push(`// TODO: Update selector for "${field}"`);
    code.push(`await ${poVar}.fillField('${field}', ds.${dataKey} as string);`);
    code.push(`enhancedLogger.info(\`✅ Entered "\${ds.${dataKey}}" into ${escapeQuotes(field)}\`, xrayTestKey);`);
  }

  // ── VERIFY / ASSERT / CHECK patterns ──
  else if (action.includes('verify') || action.includes('assert') || action.includes('check') || action.includes('confirm') || action.includes('should')) {
    if (action.includes('url')) {
      const dataKey = findDataKey(ac.testData, ['expectedUrl', 'expectedUrlFragment', 'url']);
      if (dataKey) {
        code.push(`expect(page.url()).toContain(ds.${dataKey} as string);`);
        code.push(`enhancedLogger.info(\`✅ URL contains "\${ds.${dataKey}}"\`, xrayTestKey);`);
      }
    } else if (action.includes('title')) {
      const dataKey = findDataKey(ac.testData, ['expectedTitle', 'title']);
      if (dataKey) {
        code.push(`await expect(page).toHaveTitle(new RegExp(ds.${dataKey} as string));`);
        code.push(`enhancedLogger.info(\`✅ Title matches "\${ds.${dataKey}}"\`, xrayTestKey);`);
      }
    } else if (action.includes('result') || action.includes('list') || action.includes('item') || action.includes('match')) {
      const minKey = findDataKey(ac.testData, ['expectedMinResults', 'minResults', 'resultCount']);
      if (minKey) {
        code.push(`// TODO: Update the selector for search results`);
        code.push(`const results = await ${poVar}.getResultCount();`);
        code.push(`expect(results).toBeGreaterThanOrEqual(ds.${minKey} as number);`);
        code.push(`enhancedLogger.info(\`✅ Found \${results} results (expected ≥ \${ds.${minKey}})\`, xrayTestKey);`);
      } else {
        code.push(`// TODO: Add verification logic for: "${step.action}"`);
        code.push(`enhancedLogger.info('✅ Verified: ${escapeQuotes(step.expected)}', xrayTestKey);`);
      }
    } else if (action.includes('error') || action.includes('message') || action.includes('no result') || action.includes('prompt')) {
      const msgKey = findDataKey(ac.testData, ['expectedNoResultsMessage', 'expectedErrorMessage', 'expectedMessage']);
      if (msgKey) {
        code.push(`// TODO: Update selector for message element`);
        code.push(`const message = await ${poVar}.getMessage();`);
        code.push(`expect(message).toContain(ds.${msgKey} as string);`);
        code.push(`enhancedLogger.info(\`✅ Message: "\${message}"\`, xrayTestKey);`);
      } else {
        code.push(`// TODO: Add message verification logic`);
        code.push(`enhancedLogger.info('✅ Verified: ${escapeQuotes(step.expected)}', xrayTestKey);`);
      }
    } else {
      code.push(`// TODO: Add verification logic for: "${escapeQuotes(step.action)}"`);
      code.push(`enhancedLogger.info('✅ Verified: ${escapeQuotes(step.expected)}', xrayTestKey);`);
    }
  }

  // ── DEFAULT ──
  else {
    code.push(`// TODO: Implement step ${stepNum}: "${escapeQuotes(step.action)}"`);
    code.push(`// Expected: "${escapeQuotes(step.expected)}"`);
    code.push(`enhancedLogger.info('Step ${stepNum} executed', xrayTestKey);`);
  }

  return code;
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERATOR 3: PAGE OBJECT
// ─────────────────────────────────────────────────────────────────────────────

function generatePageObject(story: UserStory): string {
  const po = story.output.pageObject;
  const lines: string[] = [];

  // Collect all unique actions across all ACs to determine methods needed
  const allActions = new Set<string>();
  for (const ac of story.acceptanceCriteria) {
    for (const step of ac.steps) {
      allActions.add(step.action.toLowerCase());
    }
  }

  const hasNavigate = [...allActions].some(a => a.includes('navigate') || a.includes('open') || a.includes('go to'));
  const hasClick    = [...allActions].some(a => a.includes('click'));
  const hasType     = [...allActions].some(a => a.includes('type') || a.includes('enter') || a.includes('search'));
  const hasSubmit   = [...allActions].some(a => a.includes('submit'));
  const hasVerifyResults = [...allActions].some(a => a.includes('result') || a.includes('list') || a.includes('item'));
  const hasVerifyMessage = [...allActions].some(a => a.includes('error') || a.includes('message') || a.includes('no result') || a.includes('prompt'));

  lines.push(`// =============================================================================`);
  lines.push(`// pages/${po}.ts — AUTO-GENERATED PAGE OBJECT`);
  lines.push(`// =============================================================================`);
  lines.push(`// SOURCE: ${story.storyId} — ${story.title}`);
  lines.push(`// GENERATED BY: npm run generate`);
  lines.push(`//`);
  lines.push(`// ⚠️  REVIEW & CUSTOMIZE:`);
  lines.push(`//   1. Update ALL selectors (marked with TODO) to match your application`);
  lines.push(`//   2. Add any additional locators your page needs`);
  lines.push(`//   3. Add helper methods specific to this page's functionality`);
  lines.push(`// =============================================================================`);
  lines.push('');
  lines.push(`import { type Page, type Locator, expect } from '@playwright/test';`);
  lines.push(`import { BasePage } from './BasePage';`);
  lines.push(`import { enhancedLogger } from '../utils/helpers/enhanced-logger';`);
  lines.push('');
  lines.push(`export class ${po} extends BasePage {`);
  lines.push('');

  // ── Locators section ──
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push(`  // LOCATORS — TODO: Update these selectors to match your application`);
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push('');

  if (hasClick) {
    lines.push(`  // TODO: Add specific locators for clickable elements on this page`);
    lines.push(`  // Example:`);
    lines.push(`  // private get searchButton() { return this.page.getByRole('button', { name: 'Search' }); }`);
    lines.push('');
  }

  if (hasType) {
    lines.push(`  // TODO: Add locators for input fields`);
    lines.push(`  // Example:`);
    lines.push(`  // private get searchInput() { return this.page.getByPlaceholder('Search docs'); }`);
    lines.push('');
  }

  if (hasVerifyResults) {
    lines.push(`  // TODO: Add locator for results container`);
    lines.push(`  // Example:`);
    lines.push(`  // private get resultsList() { return this.page.locator('.search-results li'); }`);
    lines.push('');
  }

  if (hasVerifyMessage) {
    lines.push(`  // TODO: Add locator for message/notification element`);
    lines.push(`  // Example:`);
    lines.push(`  // private get messageElement() { return this.page.locator('.search-no-results'); }`);
    lines.push('');
  }

  // ── Constructor ──
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push(`  // CONSTRUCTOR`);
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push(`  constructor(page: Page) {`);
  lines.push(`    super(page);`);
  lines.push(`  }`);
  lines.push('');

  // ── Methods ──
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push(`  // ACTIONS`);
  lines.push(`  // ════════════════════════════════════════════════════════════════════════`);
  lines.push('');

  if (hasNavigate) {
    lines.push(`  /**`);
    lines.push(`   * Navigate to a specific path on the target site.`);
    lines.push(`   */`);
    lines.push(`  async navigateTo(pagePath: string): Promise<void> {`);
    lines.push(`    enhancedLogger.section(\`📂 Navigating to \${pagePath}\`);`);
    lines.push(`    await this.navigate(pagePath);`);
    lines.push(`    await this.dismissCookieBanner();`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasClick) {
    lines.push(`  /**`);
    lines.push(`   * Click an element identified by a descriptive name.`);
    lines.push(`   * TODO: Map element names to actual locators.`);
    lines.push(`   */`);
    lines.push(`  async performClick(elementName: string): Promise<void> {`);
    lines.push(`    enhancedLogger.info(\`🖱️  Clicking: \${elementName}\`);`);
    lines.push(`    // TODO: Replace with actual locator logic`);
    lines.push(`    // Example: await this.searchButton.click();`);
    lines.push(`    const el = this.page.getByRole('button', { name: new RegExp(elementName, 'i') });`);
    lines.push(`    await el.click();`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasType) {
    lines.push(`  /**`);
    lines.push(`   * Fill a form field identified by a descriptive name.`);
    lines.push(`   * TODO: Map field names to actual locators.`);
    lines.push(`   */`);
    lines.push(`  async fillField(fieldName: string, value: string): Promise<void> {`);
    lines.push(`    enhancedLogger.info(\`✏️  Filling "\${fieldName}" with "\${value}"\`);`);
    lines.push(`    // TODO: Replace with actual locator logic`);
    lines.push(`    // Example: await this.searchInput.fill(value);`);
    lines.push(`    const el = this.page.getByPlaceholder(new RegExp(fieldName, 'i'));`);
    lines.push(`    await el.fill(value);`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasSubmit) {
    lines.push(`  /**`);
    lines.push(`   * Submit the current form.`);
    lines.push(`   * TODO: Update to match your form's submit mechanism.`);
    lines.push(`   */`);
    lines.push(`  async submitForm(): Promise<void> {`);
    lines.push(`    enhancedLogger.info('📤 Submitting form');`);
    lines.push(`    // TODO: Replace with actual submit logic`);
    lines.push(`    await this.page.getByRole('button', { name: /submit|search|go/i }).click();`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasVerifyResults) {
    lines.push(`  /**`);
    lines.push(`   * Get the count of search results / list items on the page.`);
    lines.push(`   * TODO: Update the selector to match your results list.`);
    lines.push(`   */`);
    lines.push(`  async getResultCount(): Promise<number> {`);
    lines.push(`    // TODO: Update selector`);
    lines.push(`    const items = this.page.locator('.search-results li, [class*="result"] li, [class*="hit"]');`);
    lines.push(`    const count = await items.count();`);
    lines.push(`    enhancedLogger.info(\`📊 Found \${count} results\`);`);
    lines.push(`    return count;`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasVerifyMessage) {
    lines.push(`  /**`);
    lines.push(`   * Get the text of a notification / message on the page.`);
    lines.push(`   * TODO: Update the selector to match your message element.`);
    lines.push(`   */`);
    lines.push(`  async getMessage(): Promise<string> {`);
    lines.push(`    // TODO: Update selector`);
    lines.push(`    const el = this.page.locator('.message, .notification, [class*="no-result"], [class*="empty"]').first();`);
    lines.push(`    const text = await el.textContent() || '';`);
    lines.push(`    enhancedLogger.info(\`💬 Message: "\${text}"\`);`);
    lines.push(`    return text.trim();`);
    lines.push(`  }`);
    lines.push('');
  }

  // Always add a getCurrentUrl helper
  lines.push(`  /**`);
  lines.push(`   * Get the current page URL.`);
  lines.push(`   */`);
  lines.push(`  getCurrentUrl(): string {`);
  lines.push(`    return this.page.url();`);
  lines.push(`  }`);

  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERATOR 4: TEST_CASES.md SECTION
// ─────────────────────────────────────────────────────────────────────────────

function generateTestCasesMd(story: UserStory): string {
  const lines: string[] = [];

  lines.push('');
  lines.push(`# ═══════════════════════════════════════════════════════════════════════════`);
  lines.push(`# ${story.storyId}: ${story.title.toUpperCase()} (AUTO-GENERATED)`);
  lines.push(`# ═══════════════════════════════════════════════════════════════════════════`);
  lines.push('');
  lines.push(`## 📖 User Story ${story.storyId}`);
  lines.push('');
  lines.push(`> ${story.description}`);
  lines.push('');
  lines.push(`**Priority:** ${story.priority}  `);
  lines.push(`**Module:** ${story.module}  `);
  lines.push(`**Target:** \`${story.baseUrl}\`  `);
  lines.push('');
  lines.push('**Acceptance Criteria:**');
  for (let i = 0; i < story.acceptanceCriteria.length; i++) {
    const ac = story.acceptanceCriteria[i]!;
    lines.push(`- ✅ AC-${i + 1}: ${ac.title}`);
  }
  lines.push('');
  lines.push('---');

  for (const ac of story.acceptanceCriteria) {
    lines.push('');
    lines.push(`### ${ac.tcId}: ${ac.title}`);
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    lines.push(`| **Test Case ID** | ${ac.tcId} |`);
    lines.push(`| **XRAY Key** | ${ac.id} |`);
    lines.push(`| **Priority** | ${ac.priority.charAt(0).toUpperCase() + ac.priority.slice(1)} |`);
    lines.push(`| **Type** | ${ac.type.charAt(0).toUpperCase() + ac.type.slice(1)} |`);
    lines.push('');
    lines.push('**Preconditions:**');
    for (const pre of ac.preconditions) {
      lines.push(`- ${pre}`);
    }
    lines.push('');
    lines.push('**Test Steps:**');
    lines.push('');
    lines.push('| Step | Action | Expected Result |');
    lines.push('|---|---|---|');
    for (let i = 0; i < ac.steps.length; i++) {
      const step = ac.steps[i]!;
      lines.push(`| ${i + 1} | ${step.action} | ${step.expected} |`);
    }
    lines.push('');
    lines.push('**Test Data:**');
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    for (const [key, value] of Object.entries(ac.testData)) {
      lines.push(`| ${key} | \`${value}\` |`);
    }
    lines.push('');
    lines.push('**Script Mapping:**');
    lines.push('');
    lines.push('| Attribute | Value |');
    lines.push('|---|---|');
    lines.push(`| Test File | \`tests/${story.output.testFile}\` |`);
    lines.push(`| Page Object | \`${story.output.pageObject}\` |`);
    lines.push(`| Data File | \`test-data/${story.output.dataFile}\` |`);
    lines.push(`| XRAY Key | \`${ac.id}\` |`);
    lines.push('');
    lines.push('---');
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
//  STRING UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

function varName(projId: string): string {
  // PROJ-201 → proj201
  return projId.toLowerCase().replace(/-/g, '');
}

function escapeTemplate(str: string): string {
  return str.replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function escapeQuotes(str: string): string {
  return str.replace(/'/g, "\\'").replace(/"/g, '\\"');
}

function extractTarget(action: string): string {
  // "Click the search icon / press Ctrl+K to open search" → "search icon"
  const match = action.match(/click\s+(?:the\s+)?(.+?)(?:\s+(?:to|and|button|link|tab|\/|—|–))/i);
  if (match?.[1]) return match[1].trim();
  const match2 = action.match(/click\s+(?:the\s+|on\s+)?(.+)/i);
  if (match2?.[1]) return match2[1].trim();
  // "Open the search modal" → "search modal"
  const match3 = action.match(/open\s+(?:the\s+)?(.+)/i);
  if (match3?.[1]) return match3[1].trim();
  // "Press Ctrl+K to open search" → "Ctrl+K"
  const match4 = action.match(/press\s+(.+?)(?:\s+to\b)/i);
  if (match4?.[1]) return match4[1].trim();
  return 'element';
}

function extractField(action: string): string {
  // "Type 'locator' into the search field" → "search field"
  const match = action.match(/(?:into|in)\s+(?:the\s+)?(.+?)(?:\s*field)?$/i);
  if (match?.[1]) return match[1].trim();
  return 'input';
}

function guessDataKey(action: string, testData: Record<string, unknown>): string {
  const keys = Object.keys(testData);
  // If action contains "search", try searchKeyword, keyword, query, etc.
  for (const k of keys) {
    if (action.toLowerCase().includes(k.toLowerCase().replace(/expected|min|max/gi, ''))) {
      return k;
    }
  }
  // Try common patterns
  if (action.toLowerCase().includes('search')) {
    for (const k of keys) {
      if (k.toLowerCase().includes('keyword') || k.toLowerCase().includes('query') || k.toLowerCase().includes('search')) {
        return k;
      }
    }
  }
  // Return first non-expected key
  for (const k of keys) {
    if (!k.startsWith('expected')) return k;
  }
  return keys[0] || 'value';
}

function findDataKey(testData: Record<string, unknown>, candidates: string[]): string | null {
  for (const c of candidates) {
    if (c in testData) return c;
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
//  MAIN
// ─────────────────────────────────────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2);
  const mode = args[0]; // 'tc', 'scripts', or undefined (full)
  const filterStory = args[1]; // Optional: only generate for one story file

  banner('🚀 Playwright AutoAgent — Story-to-Test Generator');

  // 1. Find all user story files
  ensureDir(STORIES_DIR);
  const storyFiles = fs.readdirSync(STORIES_DIR)
    .filter(f => f.endsWith('.yaml') || f.endsWith('.yml'))
    .filter(f => !filterStory || f.includes(filterStory));

  if (storyFiles.length === 0) {
    console.log('');
    console.log('  ❌ No user story files found in user-stories/');
    console.log('  📝 Create a YAML file in user-stories/ (see user-stories/US-05-search.yaml for template)');
    console.log('');
    process.exit(1);
  }

  console.log(`\n  📂 Found ${storyFiles.length} user story file(s):`);
  for (const f of storyFiles) {
    console.log(`     • ${f}`);
  }

  const generatedFiles: string[] = [];

  for (const storyFile of storyFiles) {
    const story = loadStory(path.join(STORIES_DIR, storyFile));
    banner(`📖 Processing: ${story.storyId} — ${story.title}`);

    // ── GENERATE TEST DATA YAML ──
    if (!mode || mode === 'tc') {
      ensureDir(TEST_DATA_DIR);
      const yamlContent = generateTestDataYaml(story);
      const yamlPath = path.join(TEST_DATA_DIR, story.output.dataFile);

      if (fs.existsSync(yamlPath)) {
        warn(`${story.output.dataFile} already exists — skipping (delete to regenerate)`);
      } else {
        fs.writeFileSync(yamlPath, yamlContent, 'utf-8');
        info(`Created: test-data/${story.output.dataFile}`);
        generatedFiles.push(`test-data/${story.output.dataFile}`);
      }
    }

    // ── GENERATE TEST_CASES.MD SECTION ──
    if (!mode || mode === 'tc') {
      const mdContent = generateTestCasesMd(story);
      const existingMd = fs.existsSync(TC_FILE) ? fs.readFileSync(TC_FILE, 'utf-8') : '';
      const marker = `# ${story.storyId}: ${story.title.toUpperCase()}`;

      if (existingMd.includes(marker)) {
        warn(`TEST_CASES.md already has section for ${story.storyId} — skipping`);
      } else {
        fs.appendFileSync(TC_FILE, mdContent, 'utf-8');
        info(`Appended to TEST_CASES.md: ${story.storyId} section`);
        generatedFiles.push('TEST_CASES.md (appended)');
      }
    }

    // ── GENERATE TEST SCRIPT ──
    if (!mode || mode === 'scripts') {
      ensureDir(TESTS_DIR);
      const scriptContent = generateTestScript(story);
      const scriptPath = path.join(TESTS_DIR, story.output.testFile);

      if (fs.existsSync(scriptPath)) {
        warn(`${story.output.testFile} already exists — skipping (delete to regenerate)`);
      } else {
        fs.writeFileSync(scriptPath, scriptContent, 'utf-8');
        info(`Created: tests/${story.output.testFile}`);
        generatedFiles.push(`tests/${story.output.testFile}`);
      }
    }

    // ── GENERATE PAGE OBJECT ──
    if (!mode || mode === 'scripts') {
      ensureDir(PAGES_DIR);
      const poContent = generatePageObject(story);
      const poPath = path.join(PAGES_DIR, `${story.output.pageObject}.ts`);

      if (fs.existsSync(poPath)) {
        warn(`${story.output.pageObject}.ts already exists — skipping (delete to regenerate)`);
      } else {
        fs.writeFileSync(poPath, poContent, 'utf-8');
        info(`Created: pages/${story.output.pageObject}.ts`);
        generatedFiles.push(`pages/${story.output.pageObject}.ts`);
      }
    }
  }

  // ── SUMMARY ──
  banner('✅ Generation Complete');
  if (generatedFiles.length === 0) {
    console.log('  No new files generated (all already exist).');
    console.log('  Delete existing generated files to regenerate them.');
  } else {
    console.log(`  Generated ${generatedFiles.length} file(s):`);
    for (const f of generatedFiles) {
      console.log(`    📄 ${f}`);
    }
  }
  console.log('');
  console.log('  📋 NEXT STEPS:');
  console.log('     1. Review generated files and customize TODO items');
  console.log('     2. Update selectors in page objects to match your application');
  console.log('     3. Run:  npm test');
  console.log('');
}

main();
